name: Custom Env Vars

on:
  workflow_dispatch:
    inputs:
      Day_Of_Week:
        description: 'Select a day of the week'
        required: true
        default: 'Funday'
      testvar:
        description: 'A test variable'
        required: false

jobs:
  mainjob:
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      First_Name: Student

    steps:
      - name: Print value of env vars
        run: |
          echo "${{ env.Greeting }} ${{ env.First_Name }}. Today is ${{ inputs.Day_Of_Week }}!"
          echo "Testvar: ${{ env.testvar }}"
