name: List all default GitHub variables

on:
  push:

jobs:
  mainjob:
    name: 'Print the default GitHub variables'
    runs-on: ubuntu-latest
    steps:
      - name: 'Print the value of environmental variables'
        run: |
          echo "$GITHUB_ACTION"
          echo "$GITHUB_ENV"
          echo "$GITHUB_API_URL"
          echo "$GITHUB_JOB"
          echo "$GITHUB_PATH"
          echo "$GITHUB_STEP_SUMMARY"
          echo "$GITHUB_WORKFLOW"